### ISSUE TITLE
Find issues to resolve for this lesson

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-webscraping#1]
This lesson has now been migrated to the Library Carpentry organisation. Work (updates, issues) should happen on THIS repo.

All the issues that need resolving are still at the old location, however: https://github.com/data-lessons/library-webscraping-DEPRECATED/issues

Find issues to resolve *there* and fix them **here**.

**Comment by pansapiens** [comment]
There are no more open issues on the old repo - should this issue be closed ?

**Comment by weaverbel** [comment]
Yep!
