### ISSUE TITLE
Incomplete XPath command in "Navigating through web-page using browser console"

### ISSUE THREAD

**Issue by charliemacquarie** [LibraryCarpentry/lc-webscraping#10]
Specifically in the examples immediately following the "Select the 'introduction' title" section:

Similar to Issue #6, I needed to add the "article" tag to make the `$x("html/body/div/blockquote")` query work. (so I changed it to: `$x("/html/body/div/article/blockquote")`)

**Comment by libcce** [comment]
@charliemacquarie this https://github.com/LibraryCarpentry/lc-webscraping/pull/15 should fix your issue?

**Comment by charliemacquarie** [comment]
Looks like it should fix the issue, thanks @libcce.
