### ISSUE TITLE
Error in walk-through of "select the challenge box" solution

### ISSUE THREAD

**Issue by lwrubel** [LibraryCarpentry/lc-webscraping#28]
In episode 2 (Xpath) there's an error in the walk-through of the challenge that involves selecting the challenge box:

`| `//`| and select the parent node of that h2 element |`

should be:

`| `..`| and select the parent node of that h2 element |`

**Comment by libcce** [comment]
Hi @lwrubel does this fix it https://github.com/LibraryCarpentry/lc-webscraping/commit/844adbfaebc9a34d8e2ce4a001feccfe0a9fcda6

**Comment by lwrubel** [comment]
Looks good to me, @libcce, thanks.
