### ISSUE TITLE
update link suggestion for case study Ep5 conclusion

### ISSUE THREAD

**Issue by ragamouf** [LibraryCarpentry/lc-webscraping#37]
Hello! The following message was sent by a community member to the Carpentries HQ inbox, passed onto the LC advisory committee, and hopefully ending up here in the best place to consider this suggestion. 

---
Hi,

Are you able to please update something on your website?

You are linking to a dead link over anchor text: "This case study" here: https://librarycarpentry.org/lc-webscraping/05-conclusion/

The link is going to this page: http://naelshiab.com/members-parliament-web-scraping/

I found a good working replacement for you here: https://prowebscraper.com/blog/data-mining-examples/

I think it's the best suitable replacement for you. Hope this helps!

**Comment by timtomch** [comment]
Thanks, I also got this message a few times. This is likely someone looking for more traffic to their (commercial) web scraping solution, but they do have a point, that link is indeed dead. I will fix it.

**Comment by timtomch** [comment]
Done. This lesson has a lot of outdated pieces, I'm trying to find the time to fix it this summer.
