### ISSUE TITLE
Changes to UK Members of Parliament

### ISSUE THREAD

**Issue by malramsay64** [LibraryCarpentry/lc-webscraping#39]
The current site for the UK house of commons has changes significantly from the example in the Manual Scraping using the Scraper extension. The nicely structured data has been replaced with a collection of `<div>` elements that is much harder to scrape automatically.

**Comment by timtomch** [comment]
Hi @malramsay64 thank you so much for offering a fix! I've been meaning to update this lesson for a while but got delayed for a variety of reasons, I'm glad you went ahead. I'll review your change today.
