### ISSUE TITLE
Scraper extension icon gives error

### ISSUE THREAD

**Issue by PhilReedData** [LibraryCarpentry/lc-webscraping#45]
I installed the Scraper Chrome extension. In Episode 3, under 'Scrape similar', there is a line: "Alternatively, the “Scrape similar” option can also be accessed from the Scraper extension icon:". When I use the extension from the icon, I get an error: "Frames are not supported at the moment. Please open the frame in a new tab or window and try scraping again." If I use the right-click page option, there is no error.
I'm using Windows 10, Chrome 86, Scraper 1.7

**Comment by timtomch** [comment]
I'm seeing the same behaviour on Mac. Looks like Scraper has some issues. We could look into suggesting another tool instead.

**Comment by timtomch** [comment]
See https://github.com/LibraryCarpentry/lc-webscraping/issues/46
