### ISSUE TITLE
Broken Link- Web Scraping 04 Web scraping using Python: requests and lxml

### ISSUE THREAD

**Issue by macyhasson** [LibraryCarpentry/lc-webscraping#9]
Setup link broken in Web scraping episode 4- Web scraping using Python: requests and lxml. Brooken Setup link is under "Introducing Requests and lxml".

https://librarycarpentry.github.io/lc-webscraping/04-lxml/

**Comment by jcoliver** [comment]
_Possibly_ fixed in #11
